#!/usr/bin/env python
# SPDX-License-Identifier: AGPL-3.0-only
"""
2D transient Warp-vs-MF6 replay/comparison harness.

This module steps the 2D Warp unconfined transient solver through every stress
period of a case and compares the resulting per-period and final heads against
a MODFLOW 6 truth artifact produced by ``working_tests/run_2d_transient_vs_mf6.py``.

The MF6 truth artifact is a compressed ``.npz.lzma`` file storing per-period
heads plus every input needed for a deterministic Warp replay: initial heads,
active/boundary masks, top/bottom elevations, hydraulic conductivity, the
per-period recharge time series, and the storage parameters (Sy, Ss).

Design notes
------------
* Time units are carried through unchanged. MF6 writes the artifact with
  ``time_units="DAYS"`` (K in m/day, recharge in m/day, ``dt = dt_days``). The
  groundwater flow equation is invariant under a rescaling of the time unit, so
  those day-valued fields are passed to Warp verbatim - the heads come out in
  metres either way. No unit conversion is applied.
* Large transient unconfined replays should start from a steady-state warm start
  rather than the raw geometric initial head. The preferred unconfined artifact
  field is ``unconfined_steady_head`` generated by the MF6 truth workflow with
  the same spatial fields and representative recharge. This keeps MF6 and Warp
  transient starts aligned and makes the first nonlinear Picard step much less
  severe. The Warp warm start must match the artifact's warm-start provenance:
  re-solving the warm start with Warp (``*_steady_warp``) while MF6 used a
  different warm start conflates warm-start error with transient error and is
  rejected by :func:`validate_warm_start_comparability` unless
  ``allow_warm_start_mismatch=True``.
* Warp's unconfined transient term is ``storage_coeff * dx**2 / dt`` per active
  non-boundary cell, so ``storage_coeff`` MUST be a storativity ``S``
  (dimensionless) - not an ambiguous MF6 parameter. Specific yield ``Sy`` is
  already a storativity component; specific storage ``Ss`` (units 1/length) is
  NOT and must be converted to a storativity by multiplying by saturated
  thickness. The replay builds an explicit storativity field via
  :func:`build_unconfined_storativity`:

    - ``phreatic_only``: ``S = Sy`` on active non-boundary water-table cells.
    - ``mf6_convertible``: ``S = Sy + Ss * saturated_thickness_ref`` where
      ``saturated_thickness_ref = clip(head_prev - bottom, min_sat, top-bottom)``,
      mirroring MF6 convertible-cell (``iconvert=1``) storage that carries both
      the phreatic ``Sy`` term and the confined elastic ``Ss * saturated_thickness``
      term. The ``Ss`` contribution is typically <1% of ``Sy`` for these cases.

  Inactive and fixed-head boundary cells carry no storage (solver convention).
* The replay can also run a confined transient comparison with
  ``formulation="confined"``. In that mode transmissivity is fixed from the
  warm-start saturated thickness and storage is ``Ss * saturated_thickness``.
* The MF6-free core (``run_warp_transient_replay``) takes plain NumPy spatial
  fields, so it can be unit-tested without Flopy or an MF6 binary. The artifact
  loader is a thin wrapper that feeds those fields plus the MF6 heads for
  comparison.
"""

from __future__ import annotations

import io
import json
import lzma
import os
import sys
import time
from pathlib import Path

import numpy as np

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

os.environ.setdefault("DARCY_FLOAT", "float64")

from DARCY_WARP_PACKAGE.project_base import data_store  # noqa: E402


DEFAULT_ARTIFACT_NAME = "mf6_transient_heads.npz.lzma"
DEFAULT_MIN_SAT = 0.1
WARM_START_ARTIFACT_INITIAL = "artifact_initial"
WARM_START_CONFINED_STEADY_MF6 = "confined_steady_mf6"
WARM_START_CONFINED_STEADY_WARP = "confined_steady_warp"
WARM_START_UNCONFINED_STEADY_MF6 = "unconfined_steady_mf6"
WARM_START_UNCONFINED_STEADY_WARP = "unconfined_steady_warp"
WARM_START_MODES = {
    WARM_START_ARTIFACT_INITIAL,
    WARM_START_CONFINED_STEADY_MF6,
    WARM_START_CONFINED_STEADY_WARP,
    WARM_START_UNCONFINED_STEADY_MF6,
    WARM_START_UNCONFINED_STEADY_WARP,
}
WARM_START_ARTIFACT_MODES = {
    WARM_START_ARTIFACT_INITIAL,
    WARM_START_CONFINED_STEADY_MF6,
    WARM_START_UNCONFINED_STEADY_MF6,
}
WARM_START_WARP_SOLVE_MODES = {
    WARM_START_CONFINED_STEADY_WARP,
    WARM_START_UNCONFINED_STEADY_WARP,
}
FORMULATION_CONFINED = "confined"
FORMULATION_UNCONFINED = "unconfined"
FORMULATION_MODES = {FORMULATION_CONFINED, FORMULATION_UNCONFINED}

# Unconfined storativity construction modes. These describe how the dimensionless
# storativity field S is built for unconfined replay; they are distinct from the
# 3D solver's own ``unconfined_storage_mode`` (``phreatic_sy`` / ``confined_volume``).
UNCONFINED_STORAGE_PHREATIC_ONLY = "phreatic_only"
UNCONFINED_STORAGE_MF6_CONVERTIBLE = "mf6_convertible"
UNCONFINED_STORAGE_MODES = {
    UNCONFINED_STORAGE_PHREATIC_ONLY,
    UNCONFINED_STORAGE_MF6_CONVERTIBLE,
}


def _warp_solver_class():
    from DARCY_WARP_PACKAGE.warped_darcy import WarpDarcySolver

    return WarpDarcySolver


def _warp_device(preferred: str = "auto") -> str:
    import warp as wp

    if preferred != "auto":
        return preferred
    try:
        return "cuda:0" if wp.is_cuda_available() else "cpu"
    except AttributeError:
        return "cuda:0"


def _load_compressed_npz(path: str | Path) -> dict:
    """Decompress a ``.npz.lzma`` fixture and return its arrays as a dict."""
    path = Path(path)
    buf = io.BytesIO(lzma.decompress(path.read_bytes()))
    with np.load(buf, allow_pickle=False) as data:
        return {key: data[key] for key in data.files}


def load_transient_artifact(path: str | Path) -> dict:
    """
    Load a 2D transient MF6 truth artifact and return its arrays.

    Returns the raw artifact arrays (per-period MF6 heads, inputs, storage
    parameters, and provenance). See module docstring for the stored fields.
    """
    arrays = _load_compressed_npz(path)
    required = (
        "heads_per_period", "heads_final", "initial_head", "active", "bc_mask",
        "bc_values", "top", "bottom", "k_field", "recharge_rates", "sy", "ss",
        "nx", "ny", "dx", "dt_days",
    )
    missing = [name for name in required if name not in arrays]
    if missing:
        raise KeyError(f"transient artifact {path} missing keys: {missing}")
    return arrays


def _scalar_string(array: object) -> str:
    return str(np.asarray(array).reshape(()))


def artifact_formulation(artifact: dict, artifact_path: str | Path | None = None) -> str | None:
    """
    Return the formulation stored in a truth artifact, including older artifacts.

    New artifacts store a direct ``formulation`` field. Older artifacts only
    carried that information in the provenance ``kind`` or, as a weaker fallback,
    in the formulation-specific output directory name.
    """
    if "formulation" in artifact:
        formulation = _scalar_string(artifact["formulation"]).strip().lower()
        if formulation in FORMULATION_MODES:
            return formulation

    provenance = artifact.get("provenance")
    if provenance is not None:
        try:
            provenance_data = json.loads(_scalar_string(provenance))
        except (TypeError, ValueError, json.JSONDecodeError):
            provenance_data = {}
        provenance_formulation = str(provenance_data.get("formulation", "")).strip().lower()
        if provenance_formulation in FORMULATION_MODES:
            return provenance_formulation
        kind = str(provenance_data.get("kind", "")).strip().lower()
        if "2d_confined_transient" in kind:
            return FORMULATION_CONFINED
        if "2d_unconfined_transient" in kind:
            return FORMULATION_UNCONFINED

    if artifact_path is not None:
        path_text = str(artifact_path).lower()
        if "mf6_transient_2d_confined" in path_text:
            return FORMULATION_CONFINED
        if "mf6_transient_2d_unconfined" in path_text:
            return FORMULATION_UNCONFINED
    return None


def require_matching_artifact_formulation(
    artifact: dict,
    requested_formulation: str,
    artifact_path: str | Path,
) -> str | None:
    artifact_mode = artifact_formulation(
        artifact=artifact,
        artifact_path=artifact_path,
    )
    if artifact_mode is not None and artifact_mode != requested_formulation:
        raise ValueError(
            f"requested formulation '{requested_formulation}' does not match MF6 artifact "
            f"formulation '{artifact_mode}' at {artifact_path}. Generate or select the "
            f"matching artifact, for example data/working_tests/mf6_transient_2d_"
            f"{requested_formulation}/{DEFAULT_ARTIFACT_NAME}."
        )
    return artifact_mode


def build_synthetic_spatial_fields(
    nx: int = 16,
    ny: int = 12,
    dx: float = 100.0,
    hydraulic_conductivity: float = 100.0,
    initial_saturated_thickness: float = 100.0,
    workspace: str | Path | None = None,
) -> dict:
    """
    Build a small, MF6-free 2D unconfined spatial field set for tests/replays.

    This mirrors the spatial construction used by the MF6 truth generator but
    uses simple rectangular top/bottom elevations so it does not depend on the
    model_builder DEM helpers. The returned dict is the same shape consumed by
    :func:`run_warp_transient_replay`.
    """
    from DARCY_WARP_PACKAGE.model_builder import (
        _build_dirichlet_boundary_mask,
        _build_domain,
    )

    active = _build_domain(nx=int(nx), ny=int(ny)).astype(np.int32)
    bc_bool = _build_dirichlet_boundary_mask(active)
    bc_mask = bc_bool.astype(np.int32)

    top = np.full((int(ny), int(nx)), 110.0, dtype=np.float64)
    bottom = np.full((int(ny), int(nx)), 10.0, dtype=np.float64)
    bc_values = np.full((int(ny), int(nx)), 100.0, dtype=np.float64)

    k_field = np.full((int(ny), int(nx)), float(hydraulic_conductivity), dtype=np.float64)
    k_field[active == 0] = 0.0

    initial_head = np.minimum(bottom + float(initial_saturated_thickness), top)
    initial_head[bc_mask != 0] = bc_values[bc_mask != 0]
    initial_head[active == 0] = 0.0

    return {
        "nx": int(nx),
        "ny": int(ny),
        "dx": float(dx),
        "active": active,
        "bc_mask": bc_mask,
        "bc_values": bc_values,
        "top": top,
        "bottom": bottom,
        "k": k_field,
        "initial_head": initial_head.astype(np.float64, copy=False),
        "workspace": Path(workspace) if workspace is not None else None,
    }


def spatial_fields_from_artifact(artifact: dict) -> dict:
    """Extract the plain-NumPy spatial fields consumed by the replay."""
    return {
        "nx": int(artifact["nx"]),
        "ny": int(artifact["ny"]),
        "dx": float(artifact["dx"]),
        "active": np.asarray(artifact["active"], dtype=np.int32),
        "bc_mask": np.asarray(artifact["bc_mask"], dtype=np.int32),
        "bc_values": np.asarray(artifact["bc_values"], dtype=np.float64),
        "top": np.asarray(artifact["top"], dtype=np.float64),
        "bottom": np.asarray(artifact["bottom"], dtype=np.float64),
        "k": np.asarray(artifact["k_field"], dtype=np.float64),
        "initial_head": np.asarray(artifact["initial_head"], dtype=np.float64),
        "workspace": None,
    }


def _initial_transmissivity(
    k: np.ndarray,
    initial_head: np.ndarray,
    top: np.ndarray,
    bottom: np.ndarray,
    active: np.ndarray,
    min_sat: float = DEFAULT_MIN_SAT,
) -> np.ndarray:
    thickness = np.maximum(
        np.asarray(initial_head, dtype=np.float64) - np.asarray(bottom, dtype=np.float64),
        float(min_sat),
    )
    full_thickness = np.maximum(
        np.asarray(top, dtype=np.float64) - np.asarray(bottom, dtype=np.float64),
        float(min_sat),
    )
    t = np.asarray(k, dtype=np.float64) * np.minimum(thickness, full_thickness)
    t[np.asarray(active, dtype=np.int32) == 0] = 0.0
    return t.astype(np.float64, copy=False)


def _confined_transmissivity(
    k: np.ndarray,
    top: np.ndarray,
    bottom: np.ndarray,
    active: np.ndarray,
    min_sat: float = DEFAULT_MIN_SAT,
) -> np.ndarray:
    """
    Build the fixed transmissivity used by MF6 confined single-layer runs.

    With ``icelltype=0`` MF6 uses the full cell thickness, not the current head
    or warm-start head, to define saturated thickness.
    """
    thickness = np.maximum(
        np.asarray(top, dtype=np.float64) - np.asarray(bottom, dtype=np.float64),
        float(min_sat),
    )
    transmissivity = np.asarray(k, dtype=np.float64) * thickness
    transmissivity[np.asarray(active, dtype=np.int32) == 0] = 0.0
    return transmissivity.astype(np.float64, copy=False)


def _confined_storage_coeff(
    ss: float,
    top: np.ndarray,
    bottom: np.ndarray,
    active: np.ndarray,
    min_sat: float = DEFAULT_MIN_SAT,
) -> np.ndarray:
    """
    Convert specific storage to MF6-equivalent confined storativity.
    """
    thickness = np.maximum(
        np.asarray(top, dtype=np.float64) - np.asarray(bottom, dtype=np.float64),
        float(min_sat),
    )
    storage = float(ss) * thickness
    storage[np.asarray(active, dtype=np.int32) == 0] = 0.0
    return storage.astype(np.float64, copy=False)


def build_unconfined_storativity(
    *,
    sy: float,
    active: np.ndarray,
    bc_mask: np.ndarray,
    ss: float = 0.0,
    head_ref: np.ndarray | None = None,
    bottom: np.ndarray | None = None,
    top: np.ndarray | None = None,
    min_sat: float = DEFAULT_MIN_SAT,
    include_specific_storage: bool = False,
) -> tuple[np.ndarray, np.ndarray | None]:
    """
    Build a dimensionless storativity field for 2D unconfined transient replay.

    Warp's transient term is ``storage_coeff * dx**2 / dt`` per active
    non-boundary cell, so ``storage_coeff`` MUST be a storativity ``S``
    (dimensionless) - not an ambiguous MF6 parameter. Specific yield ``Sy`` is
    already a storativity component; specific storage ``Ss`` (units 1/length) is
    NOT and must be converted to a storativity by multiplying by saturated
    thickness.

    * ``include_specific_storage=False`` (phreatic_only):
        ``S = Sy`` on active non-boundary water-table cells.
    * ``include_specific_storage=True`` (mf6_convertible):
        ``S = Sy + Ss * saturated_thickness_ref`` where
        ``saturated_thickness_ref = clip(head_ref - bottom, min_sat, top-bottom)``.
        This mirrors MF6 convertible-cell (``iconvert=1``) storage, which carries
        both the phreatic ``Sy`` term and the confined elastic
        ``Ss * saturated_thickness`` term. (When a cell is fully confined MF6
        drops ``Sy``; this approximation keeps ``Sy + Ss*sat_thickness`` because
        these water-table cases stay below ``top``.)

    Inactive and fixed-head boundary cells are zeroed: they carry no storage in
    the Warp 5-point transient assembly (the solver zeroes them too, so this is
    defensive and keeps the field self-describing).

    Returns ``(storativity, saturated_thickness_reference)`` where the second
    element is the saturated-thickness field used for the ``Ss`` term (or
    ``None`` when ``include_specific_storage`` is False).
    """
    active_i = np.asarray(active, dtype=np.int32)
    bcm = np.asarray(bc_mask, dtype=np.int32)
    shape = active_i.shape
    free = (active_i != 0) & (bcm == 0)

    storativity = np.full(shape, float(sy), dtype=np.float64)
    sat_ref: np.ndarray | None = None

    if include_specific_storage:
        if head_ref is None or bottom is None or top is None:
            raise ValueError(
                "include_specific_storage=True requires head_ref, bottom, and top."
            )
        head_ref = np.asarray(head_ref, dtype=np.float64)
        bottom = np.asarray(bottom, dtype=np.float64)
        top = np.asarray(top, dtype=np.float64)
        full_thickness = np.maximum(top - bottom, float(min_sat))
        sat_ref = np.clip(head_ref - bottom, float(min_sat), full_thickness)
        storativity = storativity + float(ss) * sat_ref

    # Solver convention: no storage on inactive or fixed-head boundary cells.
    storativity = storativity.copy()
    storativity[~free] = 0.0
    if sat_ref is not None:
        sat_ref = sat_ref.copy()
        sat_ref[~free] = 0.0

    return (
        storativity.astype(np.float64, copy=False),
        None if sat_ref is None else sat_ref.astype(np.float64, copy=False),
    )


def validate_warm_start_head(
    head: np.ndarray,
    spatial: dict,
    label: str = "warm_start_head",
) -> np.ndarray:
    """
    Validate and normalize a warm-start head against replay spatial fields.
    """
    h = np.asarray(head, dtype=np.float64).copy()
    shape = (int(spatial["ny"]), int(spatial["nx"]))
    if h.shape != shape:
        raise ValueError(f"{label} shape {h.shape} expected {shape}.")
    if not np.all(np.isfinite(h)):
        raise ValueError(f"{label} contains non-finite values.")

    active = np.asarray(spatial["active"], dtype=np.int32)
    bc_mask = np.asarray(spatial["bc_mask"], dtype=np.int32)
    bc_values = np.asarray(spatial["bc_values"], dtype=np.float64)
    bottom = np.asarray(spatial["bottom"], dtype=np.float64)
    top = np.asarray(spatial["top"], dtype=np.float64)

    h[active == 0] = 0.0
    h[bc_mask != 0] = bc_values[bc_mask != 0]

    free = (active != 0) & (bc_mask == 0)
    if np.any(free):
        min_allowed = bottom[free] - 1.0e-6
        max_allowed = top[free] + max(100.0, 0.1 * float(np.nanmax(top[free] - bottom[free])))
        if np.any(h[free] < min_allowed):
            raise ValueError(f"{label} has active free-cell heads below cell bottom.")
        if np.any(h[free] > max_allowed):
            raise ValueError(f"{label} has implausibly high active free-cell heads.")
    return h.astype(np.float64, copy=False)


def select_artifact_warm_start(
    artifact: dict,
    spatial: dict,
    warm_start_mode: str,
) -> tuple[np.ndarray, str]:
    """
    Select an artifact-backed warm start for replay.
    """
    mode = str(warm_start_mode).strip().lower()
    if mode not in WARM_START_ARTIFACT_MODES:
        raise ValueError(
            f"artifact warm_start_mode must be one of {sorted(WARM_START_ARTIFACT_MODES)}."
        )
    if mode == WARM_START_ARTIFACT_INITIAL:
        return validate_warm_start_head(
            head=artifact["initial_head"],
            spatial=spatial,
            label="artifact initial_head",
        ), WARM_START_ARTIFACT_INITIAL

    if mode == WARM_START_CONFINED_STEADY_MF6:
        if "confined_steady_head" not in artifact:
            raise KeyError(
                "warm_start_mode='confined_steady_mf6' requires artifact key "
                "'confined_steady_head'. Regenerate the artifact with "
                "working_tests/run_2d_transient_vs_mf6.py."
            )
        return validate_warm_start_head(
            head=artifact["confined_steady_head"],
            spatial=spatial,
            label="artifact confined_steady_head",
        ), WARM_START_CONFINED_STEADY_MF6

    if "unconfined_steady_head" not in artifact:
        raise KeyError(
            "warm_start_mode='unconfined_steady_mf6' requires artifact key "
            "'unconfined_steady_head'. Regenerate the artifact with "
            "working_tests/run_2d_transient_vs_mf6.py."
        )
    return validate_warm_start_head(
        head=artifact["unconfined_steady_head"],
        spatial=spatial,
        label="artifact unconfined_steady_head",
    ), WARM_START_UNCONFINED_STEADY_MF6


def artifact_warm_start_provenance(artifact: dict) -> str | None:
    """
    Return the ``warm_start_mode`` recorded in the artifact provenance, if any.

    The MF6 truth generator records which warm start produced the artifact's
    ``initial_head``. This is used to check that a Warp replay warm start is
    comparable to the MF6 truth.
    Returns ``None`` for artifacts without parseable warm-start provenance.
    """
    provenance = artifact.get("provenance")
    if provenance is None:
        return None
    try:
        data = json.loads(_scalar_string(provenance))
    except (TypeError, ValueError, json.JSONDecodeError):
        return None
    if not isinstance(data, dict):
        return None
    mode = str(data.get("warm_start_mode", "")).strip().lower()
    return mode or None


def validate_warm_start_comparability(
    artifact_warm_start: str | None,
    warp_warm_start_mode: str,
    allow_warm_start_mismatch: bool = False,
) -> None:
    """
    Ensure a Warp replay warm start is comparable to the MF6 artifact provenance.

    A replay must use the artifact's own transient initial condition or the same
    recorded warm-start mode. Re-solving a warm start with Warp, or selecting a
    different artifact-backed steady head, is not comparable to MF6 heads that
    started from another state. That mismatch conflates warm-start error with
    transient error and must be opted into explicitly.

    Raises ``ValueError`` on a mismatch unless ``allow_warm_start_mismatch`` is
    True. Artifacts without warm-start provenance are allowed through silently,
    and ``artifact_initial`` is always comparable because it uses the artifact's
    stored transient initial head directly.
    """
    if artifact_warm_start is None:
        return
    if warp_warm_start_mode == WARM_START_ARTIFACT_INITIAL:
        return
    if artifact_warm_start == warp_warm_start_mode:
        return
    if allow_warm_start_mismatch:
        return
    raise ValueError(
        f"Warp warm_start_mode='{warp_warm_start_mode}' does not match the MF6 "
        f"artifact warm-start provenance '{artifact_warm_start}'. That makes the "
        f"Warp-vs-MF6 head comparison invalid (warm-start error is conflated with "
        f"transient error). Use warm_start_mode='{artifact_warm_start}' or "
        f"'artifact_initial' to start from the artifact's own initial head, or pass "
        f"allow_warm_start_mismatch=True to proceed anyway."
    )


def representative_recharge_rate(recharge_rates: np.ndarray) -> float:
    rates = np.asarray(recharge_rates, dtype=np.float64).reshape(-1)
    if rates.size == 0:
        raise ValueError("recharge_rates must contain at least one value.")
    if not np.all(np.isfinite(rates)):
        raise ValueError("recharge_rates must be finite.")
    return float(np.mean(rates))


def default_solve_controls() -> dict:
    """Default Warp solve controls for the transient replay (kcycle)."""
    return {
        "max_cycles": 200,
        "max_levels": 6,
        "min_coarse_cells": 500,
        "nu_pre": 15,
        "nu_post": 15,
        "nu_coarse": 3,
        "check_every_no": 1,
        "max_outer_iterations": 100,
        "hclose": 1.0e-4,
        "rel_tol": 5.0e-7,
        "abs_tol_min": 5.0e-7,
        "dh_rms_tol": 1.0e-4,
        "residual_floor_tol": 1.0e-4,
        "smoother": "chebyshev",
        "omega": 0.7,
        "omega_min": 0.1,
        "omega_max": 0.9,
        "chebyshev_enabled": True,
        "chebyshev_order": 3,
        "cheby_lambda_min": 0.1,
        "cheby_lambda_max": 2.0,
        "chebyshev_reset_factor": 1.2,
        "chebyshev_rejection_factor": 1.2,
        "inner_forcing_eta": 0.10,
        "inner_head_residual_tol_min": 1.0e-4,
        "inner_head_residual_tol_max": 1.0e-2,
        "transmissivity_relaxation_enabled": False,
        "unconfined_startup_mode": "confined_pre_solve",
        "min_saturated_thickness": 0.1,
        "initial_saturated_thickness": 100.0,
        "max_head_change_per_outer_iteration": 10.0,
    }


def run_warp_transient_replay(
    spatial: dict,
    recharge_rates: np.ndarray,
    sy: float,
    dt: float,
    ss: float | None = None,
    n_periods: int | None = None,
    device: str = "auto",
    diag_preconditioner_backend: str = "auto",
    min_sat: float = DEFAULT_MIN_SAT,
    solve_controls: dict | None = None,
    warm_start_mode: str = WARM_START_ARTIFACT_INITIAL,
    warm_start_head: np.ndarray | None = None,
    formulation: str = FORMULATION_UNCONFINED,
    unconfined_storage_mode: str = UNCONFINED_STORAGE_PHREATIC_ONLY,
) -> dict:
    """
    Step the 2D Warp transient solver through every stress period.

    This is the MF6-free core: it takes plain NumPy spatial fields plus the
    per-period recharge rates, specific yield, and time step, and returns the
    per-period Warp heads, the final heads, the last period's convergence info,
    and timing. No Flopy/MF6 dependency.

    Parameters
    ----------
    spatial:
        Dict from :func:`build_synthetic_spatial_fields` /
        :func:`spatial_fields_from_artifact`.
    recharge_rates:
        ``(n_periods,)`` recharge rate per period (uniform in space), in the same
        time unit as ``dt``.
    sy:
        Specific yield. For unconfined replay this is the phreatic storativity
        component ``Sy`` (already dimensionless); it is NOT passed raw to the
        solver - it is folded into a storativity field by
        :func:`build_unconfined_storativity`.
    ss:
        Specific storage (1/length). For confined replay this is converted to a
        storativity as ``Ss * full_cell_thickness``. For unconfined
        ``mf6_convertible`` replay it contributes ``Ss * saturated_thickness``
        (rebuilt each period from ``head_prev``); for ``phreatic_only`` it is
        unused. ``Ss`` is never passed to the solver directly.
    dt:
        Time-step length (same unit as ``recharge_rates`` / K).
    n_periods:
        Number of periods to step. Defaults to ``len(recharge_rates)``.
    unconfined_storage_mode:
        How the unconfined storativity field is built: ``phreatic_only``
        (``S = Sy``) or ``mf6_convertible`` (``S = Sy + Ss*saturated_thickness``).
        Ignored for confined formulation.
    """
    warm_start_mode = str(warm_start_mode).strip().lower()
    if warm_start_mode not in WARM_START_MODES:
        raise ValueError(f"warm_start_mode must be one of {sorted(WARM_START_MODES)}.")
    formulation = str(formulation).strip().lower()
    if formulation not in FORMULATION_MODES:
        raise ValueError(f"formulation must be one of {sorted(FORMULATION_MODES)}.")
    if formulation == FORMULATION_CONFINED and ss is None:
        raise ValueError("formulation='confined' requires ss.")
    unconfined_storage_mode = str(unconfined_storage_mode).strip().lower()
    if unconfined_storage_mode not in UNCONFINED_STORAGE_MODES:
        raise ValueError(
            "unconfined_storage_mode must be 'phreatic_only' or 'mf6_convertible'."
        )

    explicit_control_keys = set(solve_controls.keys()) if solve_controls else set()
    controls = dict(default_solve_controls())
    if solve_controls:
        controls.update(solve_controls)

    nx = int(spatial["nx"])
    ny = int(spatial["ny"])
    dx = float(spatial["dx"])
    active = np.asarray(spatial["active"], dtype=np.int32)
    bc_mask = np.asarray(spatial["bc_mask"], dtype=np.int32)
    bc_values = np.asarray(spatial["bc_values"], dtype=np.float64)
    top = np.asarray(spatial["top"], dtype=np.float64)
    bottom = np.asarray(spatial["bottom"], dtype=np.float64)
    k = np.asarray(spatial["k"], dtype=np.float64)
    initial_head = np.asarray(spatial["initial_head"], dtype=np.float64)

    rates = np.asarray(recharge_rates, dtype=np.float64).reshape(-1)
    if n_periods is None:
        n_periods = int(rates.shape[0])
    n_periods = int(n_periods)
    if n_periods < 1:
        raise ValueError("n_periods must be >= 1.")
    if n_periods > rates.shape[0]:
        raise ValueError(
            f"n_periods={n_periods} exceeds available recharge rates ({rates.shape[0]})."
        )

    device = _warp_device(device)

    if warm_start_head is not None:
        replay_start_head = validate_warm_start_head(
            head=warm_start_head,
            spatial=spatial,
            label="warm_start_head",
        )
        warm_start_used = warm_start_mode if warm_start_mode in WARM_START_ARTIFACT_MODES else "provided"
    elif warm_start_mode == WARM_START_ARTIFACT_INITIAL:
        replay_start_head = validate_warm_start_head(
            head=initial_head,
            spatial=spatial,
            label="artifact initial_head",
        )
        warm_start_used = WARM_START_ARTIFACT_INITIAL
    elif warm_start_mode in {WARM_START_CONFINED_STEADY_MF6, WARM_START_UNCONFINED_STEADY_MF6}:
        raise ValueError(
            f"warm_start_mode='{warm_start_mode}' requires warm_start_head. "
            "Use run_replay_from_artifact so it can read the artifact warm-start head."
        )
    else:
        replay_start_head = validate_warm_start_head(
            head=initial_head,
            spatial=spatial,
            label="artifact initial_head",
        )
        warm_start_used = warm_start_mode

    warm_start_controls = dict(controls)
    transient_controls = dict(controls)
    if formulation == FORMULATION_UNCONFINED and warm_start_used != WARM_START_ARTIFACT_INITIAL and (
        "unconfined_startup_mode" not in explicit_control_keys
    ):
        # The replay already starts from a steady head, so the solver's internal
        # confined pre-solve would repeat startup work during the first
        # transient Picard step and can destabilize large-grid replays.
        transient_controls["unconfined_startup_mode"] = "initial_head"

    # Build the storativity field S (dimensionless) that the solver assembles as
    # ``storage_coeff * dx**2 / dt``. This MUST be a storativity, not a raw MF6
    # parameter: Sy is already a storativity, while Ss (1/length) is converted to
    # a storativity by multiplying by saturated thickness. See
    # :func:`build_unconfined_storativity`.
    sat_thickness_ref: np.ndarray | None = None
    if formulation == FORMULATION_CONFINED:
        initial_transmissivity = _confined_transmissivity(
            k=k,
            top=top,
            bottom=bottom,
            active=active,
            min_sat=min_sat,
        )
        # Confined storativity: Ss converted via the full cell thickness (MF6
        # icelltype=0 uses top-bottom, not the current head).
        storativity_field = _confined_storage_coeff(
            ss=float(ss),
            top=top,
            bottom=bottom,
            active=active,
            min_sat=min_sat,
        )
        storativity_kind = "ss_times_cell_thickness"
        include_specific_storage = True
        unconfined_storage_mode_resolved = None
        sat_ref_source = "full_cell_thickness"
        sat_thickness_ref = np.maximum(top - bottom, float(min_sat)).astype(np.float64, copy=False)
        sat_thickness_ref[active == 0] = 0.0
    else:
        initial_transmissivity = _initial_transmissivity(
            k=k,
            initial_head=replay_start_head,
            top=top,
            bottom=bottom,
            active=active,
            min_sat=min_sat,
        )
        unconfined_storage_mode_resolved = unconfined_storage_mode
        include_specific_storage = unconfined_storage_mode_resolved == UNCONFINED_STORAGE_MF6_CONVERTIBLE
        if include_specific_storage and ss is None:
            raise ValueError(
                "unconfined_storage_mode='mf6_convertible' requires ss (specific storage)."
            )
        storativity_kind = (
            "sy_plus_ss_times_saturated_thickness"
            if include_specific_storage
            else "sy"
        )
        sat_ref_source = "head_prev" if include_specific_storage else None
        if include_specific_storage:
            # Built per period from head_prev so the Ss*saturated_thickness term
            # tracks the water table (backward-Euler linearization).
            storativity_field = None
        else:
            storativity_field, _ = build_unconfined_storativity(
                sy=sy,
                active=active,
                bc_mask=bc_mask,
                min_sat=min_sat,
                include_specific_storage=False,
            )
    # Uniform-in-space recharge field, rebuilt per period.
    recharge_field = np.zeros((ny, nx), dtype=np.float64)

    heads_per_period = np.zeros((n_periods, ny, nx), dtype=np.float64)
    period_infos: list[dict] = []
    period_times = np.zeros(n_periods, dtype=np.float64)

    t0 = time.perf_counter()
    head_prev = replay_start_head.copy()
    actual_warm_start_head = replay_start_head.copy()
    last_info: dict = {}

    WarpDarcySolver = _warp_solver_class()
    with WarpDarcySolver(
        nx=nx,
        ny=ny,
        dx=dx,
        device=device,
        solver_type="kcycle",
        diag_preconditioner_backend=diag_preconditioner_backend,
    ) as solver:
        solver.build_from_fields(
            T_field=initial_transmissivity,
            R_field=recharge_field,
            active=active,
            bc_mask=bc_mask,
            bc_values=bc_values,
        )

        if warm_start_mode == WARM_START_CONFINED_STEADY_WARP and warm_start_head is None:
            recharge_field[...] = representative_recharge_rate(rates[:n_periods])
            recharge_field[active == 0] = 0.0
            solver.update_R_in_place(recharge_field)
            head_warm, _info_warm = solver.solve(
                formulation="confined",
                initial_head=replay_start_head,
                return_info=True,
                max_cycles=int(warm_start_controls.get("max_cycles", 40)),
                max_levels=int(warm_start_controls.get("max_levels", 5)),
                min_coarse_cells=int(warm_start_controls.get("min_coarse_cells", 1)),
                check_every_no=int(warm_start_controls.get("check_every_no", 1)),
                rel_tol=float(warm_start_controls.get("rel_tol", 5.0e-7)),
                abs_tol_min=float(warm_start_controls.get("abs_tol_min", 5.0e-7)),
                dh_rms_tol=warm_start_controls.get("dh_rms_tol"),
            )
            head_prev = validate_warm_start_head(
                head=head_warm,
                spatial=spatial,
                label="Warp confined steady warm start",
            )
            actual_warm_start_head = head_prev.copy()
        elif warm_start_mode == WARM_START_UNCONFINED_STEADY_WARP and warm_start_head is None:
            if formulation != FORMULATION_UNCONFINED:
                raise ValueError(
                    "warm_start_mode='unconfined_steady_warp' requires formulation='unconfined'."
                )
            recharge_field[...] = representative_recharge_rate(rates[:n_periods])
            recharge_field[active == 0] = 0.0
            solver.update_R_in_place(recharge_field)
            head_warm, _info_warm = solver.solve(
                formulation="unconfined",
                initial_head=replay_start_head,
                K_field=k,
                zbot_field=bottom,
                ztop_field=top,
                transient=False,
                return_info=True,
                **warm_start_controls,
            )
            head_prev = validate_warm_start_head(
                head=head_warm,
                spatial=spatial,
                label="Warp unconfined steady warm start",
            )
            actual_warm_start_head = head_prev.copy()

        for per in range(n_periods):
            rate = float(rates[per])
            recharge_field[...] = rate
            recharge_field[active == 0] = 0.0
            solver.update_R_in_place(recharge_field)

            if formulation == FORMULATION_UNCONFINED and include_specific_storage:
                # Rebuild storativity each period so the Ss*saturated_thickness
                # term follows the previous period's water table.
                storativity_field, sat_thickness_ref = build_unconfined_storativity(
                    sy=sy,
                    ss=float(ss),
                    head_ref=head_prev,
                    bottom=bottom,
                    top=top,
                    active=active,
                    bc_mask=bc_mask,
                    min_sat=min_sat,
                    include_specific_storage=True,
                )

            t_per = time.perf_counter()
            solve_kwargs = {
                "formulation": formulation,
                "initial_head": head_prev,
                "transient": True,
                "storage_coeff": storativity_field,
                "dt": float(dt),
                "head_prev": head_prev,
                "return_info": True,
                **transient_controls,
            }
            if formulation == FORMULATION_UNCONFINED:
                solve_kwargs.update(
                    {
                        "K_field": k,
                        "zbot_field": bottom,
                        "ztop_field": top,
                    }
                )
            head, info = solver.solve(**solve_kwargs)
            period_times[per] = time.perf_counter() - t_per

            head = np.asarray(head, dtype=np.float64)
            heads_per_period[per] = head
            head_prev = head
            last_info = dict(info) if isinstance(info, dict) else {}
            period_infos.append(last_info)

    total_time = time.perf_counter() - t0

    return {
        "heads_per_period": heads_per_period,
        "heads_final": heads_per_period[-1],
        "period_infos": period_infos,
        "last_info": last_info,
        "period_times": period_times,
        "total_time": total_time,
        "n_periods": n_periods,
        "device": device,
        # Explicit storativity semantics (dimensionless S). The solver assembles
        # ``storage_coeff * dx**2 / dt``, so this MUST be a storativity, not a raw
        # MF6 parameter. ``storativity`` is the field passed for the final period
        # (for mf6_convertible it is rebuilt each period from head_prev).
        "storativity": storativity_field,
        "storativity_kind": storativity_kind,
        "include_specific_storage": include_specific_storage,
        "unconfined_storage_mode": unconfined_storage_mode_resolved,
        "saturated_thickness_reference": sat_thickness_ref,
        "saturated_thickness_reference_source": sat_ref_source,
        "dt": float(dt),
        "formulation": formulation,
        "solve_controls": transient_controls,
        "warm_start_mode": warm_start_mode,
        "warm_start_used": warm_start_used,
        "warm_start_head": actual_warm_start_head,
        # Deprecated aliases (kept for backward compatibility; prefer the
        # storativity* keys above):
        "storage_coeff": storativity_field,
        "storage_coeff_kind": storativity_kind,
    }


def _head_metrics(warp_heads: np.ndarray, mf6_heads: np.ndarray, active: np.ndarray) -> dict:
    warp_heads = np.asarray(warp_heads, dtype=np.float64)
    mf6_heads = np.asarray(mf6_heads, dtype=np.float64)
    mask = (np.asarray(active) != 0) & np.isfinite(warp_heads) & np.isfinite(mf6_heads)
    diff = warp_heads - mf6_heads
    diff_masked = diff[mask]
    abs_diff = np.abs(diff_masked)
    return {
        "rmse": float(np.sqrt(np.mean(diff_masked * diff_masked))) if diff_masked.size else None,
        "max_abs_diff": float(np.max(abs_diff)) if abs_diff.size else None,
        "mean_bias_warp_minus_mf6": float(np.mean(diff_masked)) if diff_masked.size else None,
        "percent_within_0_01m": float(np.mean(abs_diff <= 0.01) * 100.0) if abs_diff.size else None,
        "percent_within_0_1m": float(np.mean(abs_diff <= 0.1) * 100.0) if abs_diff.size else None,
        "n_active": int(mask.sum()),
    }


def _field_stats(field: np.ndarray | None, active: np.ndarray) -> dict | None:
    """JSON-safe min/max/mean of a storage field over active cells."""
    if field is None:
        return None
    arr = np.asarray(field, dtype=np.float64)
    mask = np.asarray(active, dtype=np.int32) != 0
    vals = arr[mask]
    if vals.size == 0:
        return None
    return {
        "min": float(np.min(vals)),
        "max": float(np.max(vals)),
        "mean": float(np.mean(vals)),
    }


def _sat_ref_summary(
    field: np.ndarray | None,
    source: str | None,
    active: np.ndarray,
) -> dict | None:
    """JSON-safe summary of the saturated-thickness reference used for the Ss term."""
    stats = _field_stats(field, active)
    if stats is None or source is None:
        return None
    return {"source": source, **stats}


def compare_transient(
    warp_result: dict,
    mf6_heads_per_period: np.ndarray,
    mf6_heads_final: np.ndarray,
    active: np.ndarray,
) -> dict:
    """
    Compare Warp per-period/final heads against MF6 truth.

    Returns per-period metrics, final metrics, and the worst (max-abs-diff)
    period index.
    """
    warp_hpp = np.asarray(warp_result["heads_per_period"], dtype=np.float64)
    mf6_hpp = np.asarray(mf6_heads_per_period, dtype=np.float64)
    if warp_hpp.shape != mf6_hpp.shape:
        raise ValueError(
            f"per-period head shape mismatch: warp {warp_hpp.shape}, mf6 {mf6_hpp.shape}"
        )

    per_period = [
        _head_metrics(warp_hpp[i], mf6_hpp[i], active) for i in range(warp_hpp.shape[0])
    ]
    final = _head_metrics(warp_result["heads_final"], mf6_heads_final, active)

    max_abs_values = [m["max_abs_diff"] for m in per_period if m["max_abs_diff"] is not None]
    worst_period = int(np.argmax(max_abs_values)) if max_abs_values else None

    return {
        "per_period": per_period,
        "final": final,
        "worst_period": worst_period,
    }


def save_summary(path: str | Path, summary: dict) -> Path:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w") as f:
        json.dump(summary, f, indent=4, default=str)
    return path


def run_replay_from_artifact(
    artifact_path: str | Path,
    workspace: str | Path | None = None,
    device: str = "auto",
    diag_preconditioner_backend: str = "auto",
    solve_controls: dict | None = None,
    warm_start_mode: str = WARM_START_UNCONFINED_STEADY_MF6,
    formulation: str = FORMULATION_UNCONFINED,
    unconfined_storage_mode: str = UNCONFINED_STORAGE_MF6_CONVERTIBLE,
    allow_warm_start_mismatch: bool = False,
) -> dict:
    """
    Load the MF6 truth artifact, replay Warp through every period, compare, save.

    Returns the full summary dict and writes ``transient_replay_summary.json``
    plus ``warp_transient_heads.npz`` under the workspace.

    By default the replay starts from the artifact's own
    ``unconfined_steady_head`` (``unconfined_steady_mf6``) and builds an
    MF6-matching convertible storativity field (``mf6_convertible``:
    ``S = Sy + Ss*saturated_thickness``). Starting from a different warm start
    than the artifact used is rejected unless
    ``allow_warm_start_mismatch=True``.
    """
    artifact_path = Path(artifact_path)
    if workspace is None:
        workspace = artifact_path.parent
    workspace = Path(workspace)
    workspace.mkdir(parents=True, exist_ok=True)

    artifact = load_transient_artifact(artifact_path)
    spatial = spatial_fields_from_artifact(artifact)
    spatial["workspace"] = workspace
    formulation = str(formulation).strip().lower()
    if formulation not in FORMULATION_MODES:
        raise ValueError(f"formulation must be one of {sorted(FORMULATION_MODES)}.")
    artifact_mode = require_matching_artifact_formulation(
        artifact=artifact,
        requested_formulation=formulation,
        artifact_path=artifact_path,
    )
    warm_start_mode = str(warm_start_mode).strip().lower()
    if warm_start_mode not in WARM_START_MODES:
        raise ValueError(f"warm_start_mode must be one of {sorted(WARM_START_MODES)}.")
    unconfined_storage_mode = str(unconfined_storage_mode).strip().lower()
    if (
        formulation == FORMULATION_UNCONFINED
        and unconfined_storage_mode not in UNCONFINED_STORAGE_MODES
    ):
        raise ValueError(
            "unconfined_storage_mode must be 'phreatic_only' or 'mf6_convertible'."
        )

    # The Warp warm start must be comparable to the MF6 artifact's warm-start
    # provenance. Re-solving the warm start with Warp (confined_steady_warp)
    # while MF6 used its own confined solve (confined_steady_mf6) or the raw
    # artifact_initial head conflates warm-start error with transient error and
    # invalidates the head-to-head comparison.
    artifact_warm_start = artifact_warm_start_provenance(artifact)
    validate_warm_start_comparability(
        artifact_warm_start=artifact_warm_start,
        warp_warm_start_mode=warm_start_mode,
        allow_warm_start_mismatch=allow_warm_start_mismatch,
    )

    if warm_start_mode in WARM_START_WARP_SOLVE_MODES:
        warm_start_head = None
        warm_start_used = warm_start_mode
    else:
        warm_start_head, warm_start_used = select_artifact_warm_start(
            artifact=artifact,
            spatial=spatial,
            warm_start_mode=warm_start_mode,
        )

    sy = float(artifact["sy"])
    ss = float(artifact["ss"])
    dt = float(artifact["dt_days"])
    recharge_rates = np.asarray(artifact["recharge_rates"], dtype=np.float64)
    n_periods = int(recharge_rates.shape[0])

    print(f"Transient replay: {spatial['nx']}x{spatial['ny']}, {n_periods} periods, dt={dt}")
    if formulation == FORMULATION_UNCONFINED:
        if unconfined_storage_mode == UNCONFINED_STORAGE_MF6_CONVERTIBLE:
            print(
                f"  formulation: unconfined; storativity S = Sy + Ss*saturated_thickness "
                f"(Sy={sy}, Ss={ss}, mf6_convertible)"
            )
        else:
            print(
                f"  formulation: unconfined; storativity S = Sy (Sy={sy}, phreatic_only; "
                f"Ss={ss} not included)"
            )
    else:
        print(f"  formulation: confined; storativity S = Ss*full_thickness (Ss={ss})")
    print(f"  warm start: {warm_start_used} (artifact provenance: {artifact_warm_start})")
    print(f"  artifact: {artifact_path}")

    warp_result = run_warp_transient_replay(
        spatial=spatial,
        recharge_rates=recharge_rates,
        sy=sy,
        ss=ss,
        dt=dt,
        n_periods=n_periods,
        device=device,
        diag_preconditioner_backend=diag_preconditioner_backend,
        solve_controls=solve_controls,
        warm_start_mode=warm_start_used,
        warm_start_head=warm_start_head,
        formulation=formulation,
        unconfined_storage_mode=unconfined_storage_mode,
    )

    comparison = compare_transient(
        warp_result,
        np.asarray(artifact["heads_per_period"], dtype=np.float64),
        np.asarray(artifact["heads_final"], dtype=np.float64),
        spatial["active"],
    )

    # Quantify how far the Warp warm start is from the artifact's initial_head
    # (the head MF6 started period 0 from). Near-zero when Warp reuses the
    # artifact warm start; nonzero when Warp re-solves its own warm start.
    warm_start_vs_initial = _head_metrics(
        np.asarray(warp_result["warm_start_head"], dtype=np.float64),
        np.asarray(artifact["initial_head"], dtype=np.float64),
        spatial["active"],
    )

    warp_npz = workspace.joinpath("warp_transient_heads.npz")
    sat_ref_field = warp_result["saturated_thickness_reference"]
    period_infos = warp_result.get("period_infos")
    if not isinstance(period_infos, list):
        period_infos = [warp_result["last_info"]]
    np.savez_compressed(
        warp_npz,
        heads_per_period=warp_result["heads_per_period"],
        heads_final=warp_result["heads_final"],
        total_time=np.asarray(warp_result["total_time"], dtype=np.float64),
        period_times=warp_result["period_times"],
        last_info=np.asarray(json.dumps(warp_result["last_info"], default=str)),
        period_infos=np.asarray(json.dumps(period_infos, default=str)),
        warp_storativity=np.asarray(warp_result["storativity"], dtype=np.float64),
        warp_storativity_kind=np.asarray(warp_result["storativity_kind"]),
        include_specific_storage=np.asarray(warp_result["include_specific_storage"]),
        unconfined_storage_mode=np.asarray(
            warp_result["unconfined_storage_mode"]
            if warp_result["unconfined_storage_mode"] is not None
            else "none"
        ),
        saturated_thickness_reference=(
            np.asarray(sat_ref_field, dtype=np.float64)
            if sat_ref_field is not None
            else np.asarray([], dtype=np.float64)
        ),
        dt=np.asarray(warp_result["dt"], dtype=np.float64),
        formulation=np.asarray(warp_result["formulation"]),
        device=np.asarray(warp_result["device"]),
        warm_start_mode=np.asarray(warp_result["warm_start_mode"]),
        warm_start_used=np.asarray(warp_result["warm_start_used"]),
        warm_start_head=np.asarray(warp_result["warm_start_head"], dtype=np.float64),
        # Deprecated aliases:
        storage_coeff=np.asarray(warp_result["storativity"], dtype=np.float64),
        storage_coeff_kind=np.asarray(warp_result["storativity_kind"]),
    )

    provenance = artifact.get("provenance")
    if provenance is not None:
        provenance = str(np.asarray(provenance).reshape(()))
    mf6_transient_total_time = _scalar(artifact, "total_time")
    mf6_transient_engine_time = _scalar(artifact, "engine_time")
    mf6_confined_steady_engine_time = _scalar(artifact, "confined_steady_engine_time")
    mf6_unconfined_steady_engine_time = _scalar(artifact, "unconfined_steady_engine_time")
    mf6_combined_engine_time = None
    if mf6_transient_engine_time is not None:
        mf6_combined_engine_time = mf6_transient_engine_time
        if mf6_confined_steady_engine_time is not None and np.isfinite(mf6_confined_steady_engine_time):
            mf6_combined_engine_time += mf6_confined_steady_engine_time
        if mf6_unconfined_steady_engine_time is not None and np.isfinite(mf6_unconfined_steady_engine_time):
            mf6_combined_engine_time += mf6_unconfined_steady_engine_time

    # Storativity is zero on inactive/boundary cells by convention, so report
    # field statistics over active non-boundary (free) cells only.
    free_mask = (np.asarray(spatial["active"], dtype=np.int32) != 0) & (
        np.asarray(spatial["bc_mask"], dtype=np.int32) == 0
    )

    summary = {
        "artifact_path": str(artifact_path),
        "artifact_formulation": artifact_mode,
        "grid": {"nx": spatial["nx"], "ny": spatial["ny"], "dx": spatial["dx"]},
        "n_periods": n_periods,
        "dt": dt,
        "formulation": formulation,
        "storage": {
            "sy": sy,
            "ss": ss,
            "unconfined_storage_mode": warp_result["unconfined_storage_mode"],
            "warp_storativity": _field_stats(warp_result["storativity"], free_mask),
            "warp_storativity_kind": warp_result["storativity_kind"],
            "include_specific_storage": warp_result["include_specific_storage"],
            "saturated_thickness_reference": _sat_ref_summary(
                warp_result["saturated_thickness_reference"],
                warp_result["saturated_thickness_reference_source"],
                free_mask,
            ),
            # Deprecated aliases (use warp_storativity* above):
            "warp_storage_coeff": _field_stats(warp_result["storativity"], free_mask),
            "warp_storage_coeff_kind": warp_result["storativity_kind"],
        },
        "warm_start": {
            "requested": warm_start_mode,
            "used": warp_result["warm_start_used"],
            "source": warm_start_used,
            "artifact_provenance": artifact_warm_start,
            "allow_warm_start_mismatch": bool(allow_warm_start_mismatch),
            "warm_start_vs_initial_head": warm_start_vs_initial,
        },
        "timing": {
            "warp_total_time": float(warp_result["total_time"]),
            "mf6_total_time": mf6_transient_total_time,
            "mf6_engine_time": mf6_transient_engine_time,
            "mf6_transient_total_time": mf6_transient_total_time,
            "mf6_transient_engine_time": mf6_transient_engine_time,
            "mf6_confined_steady_engine_time": mf6_confined_steady_engine_time,
            "mf6_unconfined_steady_engine_time": mf6_unconfined_steady_engine_time,
            "mf6_engine_time_including_warm_start": mf6_combined_engine_time,
            "warp_period_time_mean": float(np.mean(warp_result["period_times"])),
            "warp_period_time_max": float(np.max(warp_result["period_times"])),
        },
        "convergence": _summarize_last_info(warp_result["last_info"]),
        "period_convergence": _summarize_period_infos(period_infos),
        "warp_head_stats": _summarize_period_head_stats(
            heads_per_period=warp_result["heads_per_period"],
            active=spatial["active"],
            bc_mask=spatial["bc_mask"],
        ),
        "solve_settings": warp_result["solve_controls"],
        "device": warp_result["device"],
        "diag_preconditioner_backend": diag_preconditioner_backend,
        "comparison": comparison,
        "mf6_provenance": provenance,
    }

    summary_path = workspace.joinpath("transient_replay_summary.json")
    save_summary(summary_path, summary)

    print(f"Warp transient heads saved to {warp_npz}")
    print(f"Replay summary saved to {summary_path}")
    final_max = comparison["final"]["max_abs_diff"]
    final_rmse = comparison["final"]["rmse"]
    print(
        f"Final vs MF6: max_abs_diff={final_max:.6g} m, rmse={final_rmse:.6g} m "
        f"(worst period {comparison['worst_period']})"
    )
    return summary


def _scalar(artifact: dict, name: str) -> float | None:
    if name not in artifact:
        return None
    try:
        return float(np.asarray(artifact[name]).reshape(()))
    except (TypeError, ValueError):
        return None


def _summarize_last_info(info: dict) -> dict:
    if not isinstance(info, dict):
        return {}
    keys = (
        "converged", "outer_iterations", "formulation", "transient",
        "final_max_abs_head_change", "final_residual", "chebyshev_rejections",
        "chebyshev_resets", "accepted_picard_update_count",
        "strict_inner_nonconvergence_count", "unusable_inner_solve_count",
        "practical_inner_acceptance_count", "effectively_dry_cell_count",
    )
    out = {}
    for key in keys:
        if key in info:
            value = info[key]
            if isinstance(value, (int, np.integer)):
                out[key] = int(value)
            elif isinstance(value, (float, np.floating)):
                out[key] = float(value)
            else:
                out[key] = value
    return out


def _summary_value(value):
    if isinstance(value, (bool, np.bool_)):
        return bool(value)
    if isinstance(value, (int, np.integer)):
        return int(value)
    if isinstance(value, (float, np.floating)):
        value_f = float(value)
        return value_f if np.isfinite(value_f) else None
    if value is None:
        return None
    return value


def _summarize_period_infos(period_infos: list[dict]) -> dict:
    if not isinstance(period_infos, list):
        return {"n_periods": 0, "all_converged": False, "periods": []}

    keys = (
        "converged",
        "outer_iterations",
        "final_max_abs_head_change",
        "final_residual",
        "picard_max_iter",
        "picard_dh_max_end",
        "strict_inner_nonconvergence_count",
        "unusable_inner_solve_count",
        "practical_inner_acceptance_count",
        "accepted_picard_update_count",
        "inner_usable_for_picard",
        "inner_h_rms_end",
        "inner_max_cycles_used",
        "effectively_dry_cell_count",
    )

    periods = []
    first_nonconverged_period = None
    for period_index, info in enumerate(period_infos, start=1):
        period_summary = {"period": int(period_index)}
        if isinstance(info, dict):
            for key in keys:
                if key in info:
                    period_summary[key] = _summary_value(info[key])
        converged = bool(period_summary.get("converged", False))
        if not converged and first_nonconverged_period is None:
            first_nonconverged_period = int(period_index)
        periods.append(period_summary)

    return {
        "n_periods": int(len(periods)),
        "all_converged": first_nonconverged_period is None and len(periods) > 0,
        "first_nonconverged_period": first_nonconverged_period,
        "periods": periods,
    }


def _summarize_period_head_stats(
    *,
    heads_per_period: np.ndarray,
    active: np.ndarray,
    bc_mask: np.ndarray,
) -> list[dict]:
    heads = np.asarray(heads_per_period, dtype=np.float64)
    active_i = np.asarray(active, dtype=np.int32)
    bc_i = np.asarray(bc_mask, dtype=np.int32)
    free = (active_i != 0) & (bc_i == 0)

    summaries: list[dict] = []
    for period_index in range(heads.shape[0]):
        period_heads = heads[period_index]
        mask = free & np.isfinite(period_heads)
        values = period_heads[mask]
        if values.size == 0:
            summaries.append(
                {
                    "period": int(period_index + 1),
                    "n_free": 0,
                    "min": None,
                    "max": None,
                    "mean": None,
                    "std": None,
                }
            )
            continue
        summaries.append(
            {
                "period": int(period_index + 1),
                "n_free": int(values.size),
                "min": float(np.min(values)),
                "max": float(np.max(values)),
                "mean": float(np.mean(values)),
                "std": float(np.std(values)),
            }
        )
    return summaries


def default_artifact_path(formulation: str = FORMULATION_UNCONFINED) -> Path:
    formulation = str(formulation).strip().lower()
    if formulation not in FORMULATION_MODES:
        raise ValueError(f"formulation must be one of {sorted(FORMULATION_MODES)}.")
    return data_store.joinpath(
        "working_tests", f"mf6_transient_2d_{formulation}", DEFAULT_ARTIFACT_NAME
    )


def main(
    artifact_path: str | Path | None = None,
    workspace: str | Path | None = None,
    device: str = "auto",
    diag_preconditioner_backend: str = "auto",
    warm_start_mode: str = WARM_START_UNCONFINED_STEADY_MF6,
    formulation: str = FORMULATION_UNCONFINED,
    unconfined_storage_mode: str = UNCONFINED_STORAGE_MF6_CONVERTIBLE,
    allow_warm_start_mismatch: bool = False,
) -> dict:
    """
    Run the default transient replay against the MF6 truth artifact.

    If the artifact is missing, prints instructions to generate it rather than
    failing, so importing this module never requires MF6 to be installed.
    """
    formulation = str(formulation).strip().lower()
    if formulation not in FORMULATION_MODES:
        raise ValueError(f"formulation must be one of {sorted(FORMULATION_MODES)}.")
    artifact_path = (
        Path(artifact_path)
        if artifact_path is not None
        else default_artifact_path(formulation=formulation)
    )
    if not artifact_path.exists():
        print(f"MF6 transient artifact not found at {artifact_path}.")
        print(
            "Generate it first with:  python working_tests/run_2d_transient_vs_mf6.py "
            f"(formulation={formulation})"
        )
        return {"artifact_path": str(artifact_path), "ran": False}
    return run_replay_from_artifact(
        artifact_path=artifact_path,
        workspace=workspace,
        device=device,
        diag_preconditioner_backend=diag_preconditioner_backend,
        warm_start_mode=warm_start_mode,
        formulation=formulation,
        unconfined_storage_mode=unconfined_storage_mode,
        allow_warm_start_mismatch=allow_warm_start_mismatch,
    )


if __name__ == "__main__":
    # Configuration parameters
    artifact_path = None                 # defaults to the standard MF6 truth artifact
    workspace = None                     # defaults to the artifact's parent directory
    device = "auto"
    diag_preconditioner_backend = "device"
    # Default to the artifact's own unconfined steady head so the Warp-vs-MF6
    # comparison starts from a steady water table. Override to a Warp-resolved
    # warm start only with allow_warm_start_mismatch=True.
    warm_start_mode = WARM_START_UNCONFINED_STEADY_WARP
    formulation = FORMULATION_UNCONFINED
    unconfined_storage_mode = UNCONFINED_STORAGE_MF6_CONVERTIBLE
    allow_warm_start_mismatch = True
    main(
        artifact_path=artifact_path,
        workspace=workspace,
        device=device,
        diag_preconditioner_backend=diag_preconditioner_backend,
        warm_start_mode=warm_start_mode,
        formulation=formulation,
        unconfined_storage_mode=unconfined_storage_mode,
        allow_warm_start_mismatch=allow_warm_start_mismatch,
    )
